language: node_js
node_js:
  - 10
install: npm install
jobs:
  include:
    - stage: deploy
      node_js: 10
      script: bash ./deploy.sh
cache:
  directories:
    - node_modules
dist: trusty
sudo: false